name: Build and deploy

on:
  push:
    branches:
      - action
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js version and run custom command
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider

      - name: npm install, build, and test
        run: |
          npm install
          npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .
