name: Helm List on Commit to Master

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  helm-list:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Kubernetes credentials
      run: |
        mkdir -p ~/.kube
        echo "$KUBECONFIG_CONTENT" > ~/.kube/config

    - name: Verify Kubernetes connectivity
      run: |
        kubectl get nodes --kubeconfig ~/.kube/config

    - name: List Helm Releases in ingress-nginx namespace
      run: |
        helm version
        helm list -n ingress-nginx
      env:
        KUBECONFIG_CONTENT: '${{ secrets.KUBECONFIG_CONTENT }}'
