name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  test-helm:
    runs-on: self-hosted
    steps:
      - name: Set up Kubernetes credentials
        run: |
          echo "$KUBECONFIG_CONTENT" > ~/.kube/config
          helm version
          helm list -n ingress-nginx
