name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  test-helm:
    runs-on: self-hosted
    steps:
      - name: Ensure Helm is available
        run: |
          echo "Helm is installed in: $(which helm)"
          helm version
          helm list -n ingress-nginx
